// <auto-generated />
using System;
using FlagForge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlagForge.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FlagForge.Data.Models.FeatureFlag", b =>
        {
            b.Property<Guid>("FlagId").HasColumnType("uuid");
            b.Property<bool>("Enabled").HasColumnType("boolean");
            b.Property<Guid>("EnvironmentId").HasColumnType("uuid");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("Rules").IsRequired().HasColumnType("jsonb").HasDefaultValue("{}");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<long>("Version").HasColumnType("bigint");

            b.HasKey("FlagId");
            b.HasIndex("EnvironmentId", "Name").IsUnique();
            b.HasIndex("EnvironmentId", "Version");
            b.ToTable("FeatureFlags", (string)null);
        });

        modelBuilder.Entity("FlagForge.Data.Models.FeatureFlagEnvironment", b =>
        {
            b.Property<Guid>("EnvironmentId").HasColumnType("uuid");
            b.Property<string>("ApiKey").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");

            b.HasKey("EnvironmentId");
            b.HasIndex("ApiKey").IsUnique();
            b.HasIndex("TenantId", "Name").IsUnique();
            b.ToTable("Environments", (string)null);
        });

        modelBuilder.Entity("FlagForge.Data.Models.Tenant", b =>
        {
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("Plan").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");

            b.HasKey("TenantId");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Tenants", (string)null);
        });

        modelBuilder.Entity("FlagForge.Data.Models.UsageAuditLog", b =>
        {
            b.Property<Guid>("LogId").HasColumnType("uuid");
            b.Property<Guid>("EnvironmentId").HasColumnType("uuid");
            b.Property<bool>("EvaluationResult").HasColumnType("boolean");
            b.Property<string>("FlagName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("Timestamp").HasColumnType("timestamp with time zone");

            b.HasKey("LogId");
            b.HasIndex("EnvironmentId", "Timestamp");
            b.HasIndex("TenantId", "Timestamp");
            b.ToTable("UsageAuditLogs", (string)null);
        });

        modelBuilder.Entity("FlagForge.Data.Models.FeatureFlag", b =>
        {
            b.HasOne("FlagForge.Data.Models.FeatureFlagEnvironment", "Environment")
                .WithMany("FeatureFlags")
                .HasForeignKey("EnvironmentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Environment");
        });

        modelBuilder.Entity("FlagForge.Data.Models.FeatureFlagEnvironment", b =>
        {
            b.HasOne("FlagForge.Data.Models.Tenant", "Tenant")
                .WithMany("Environments")
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Tenant");
        });

        modelBuilder.Entity("FlagForge.Data.Models.UsageAuditLog", b =>
        {
            b.HasOne("FlagForge.Data.Models.FeatureFlagEnvironment", "Environment")
                .WithMany()
                .HasForeignKey("EnvironmentId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("FlagForge.Data.Models.Tenant", "Tenant")
                .WithMany()
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Environment");
            b.Navigation("Tenant");
        });

        modelBuilder.Entity("FlagForge.Data.Models.FeatureFlagEnvironment", b =>
        {
            b.Navigation("FeatureFlags");
        });

        modelBuilder.Entity("FlagForge.Data.Models.Tenant", b =>
        {
            b.Navigation("Environments");
        });
#pragma warning restore 612, 618
    }
}
